-- Pivka v2 / Phase 1 foundation
create extension if not exists pgcrypto;

create type public.app_role as enum ('OWNER','ADMIN','STAFF','DRIVER');
create type public.order_status as enum ('NEW','CONFIRMED','PREPARING','OUT_FOR_DELIVERY','DELIVERED','CANCELLED','REFUNDED');
create type public.payment_status as enum ('PENDING','PAID','FAILED','REFUNDED');
create type public.inventory_movement_type as enum ('PURCHASE','SALE','BUNDLE_SALE','GIFT','RETURN','CANCELLATION','WRITE_OFF','MANUAL_ADJUSTMENT');

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  phone text,
  role public.app_role not null default 'STAFF',
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table public.categories (
  id uuid primary key default gen_random_uuid(),
  slug text unique not null,
  name text not null,
  emoji text,
  sort_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table public.products (
  id uuid primary key default gen_random_uuid(),
  sku text unique not null,
  category_id uuid references public.categories(id),
  name text not null,
  description text,
  image_url text,
  unit text not null check (unit in ('liter','bottle','piece','kg','pack')),
  sale_price numeric(12,2) not null default 0 check (sale_price >= 0),
  purchase_price numeric(12,2) not null default 0 check (purchase_price >= 0),
  stock_quantity numeric(12,3) not null default 0,
  minimum_quantity numeric(12,3) not null default 1 check (minimum_quantity > 0),
  quantity_step numeric(12,3) not null default 1 check (quantity_step > 0),
  active boolean not null default true,
  featured boolean not null default false,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.customers (
  id uuid primary key default gen_random_uuid(),
  phone text unique not null,
  full_name text,
  created_at timestamptz not null default now(),
  last_order_at timestamptz
);

create table public.customer_addresses (
  id uuid primary key default gen_random_uuid(),
  customer_id uuid not null references public.customers(id) on delete cascade,
  label text,
  address text not null,
  is_default boolean not null default false,
  created_at timestamptz not null default now()
);

create table public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number bigint generated by default as identity unique,
  customer_id uuid references public.customers(id),
  status public.order_status not null default 'NEW',
  fulfillment_type text not null default 'pickup' check (fulfillment_type in ('pickup','delivery')),
  address_snapshot text,
  payment_method text,
  payment_status public.payment_status not null default 'PENDING',
  subtotal numeric(12,2) not null default 0,
  discount_total numeric(12,2) not null default 0,
  gift_cost_total numeric(12,2) not null default 0,
  delivery_fee numeric(12,2) not null default 0,
  total numeric(12,2) not null default 0,
  cogs_total numeric(12,2) not null default 0,
  gross_profit numeric(12,2) not null default 0,
  comment text,
  created_at timestamptz not null default now(),
  confirmed_at timestamptz,
  delivered_at timestamptz,
  cancelled_at timestamptz
);

create table public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id uuid references public.products(id),
  item_type text not null default 'PRODUCT' check (item_type in ('PRODUCT','BUNDLE','GIFT')),
  name_snapshot text not null,
  sku_snapshot text,
  unit_snapshot text,
  quantity numeric(12,3) not null check (quantity > 0),
  unit_price_snapshot numeric(12,2) not null,
  unit_cost_snapshot numeric(12,2) not null default 0,
  line_total numeric(12,2) not null,
  line_cogs numeric(12,2) not null default 0
);

create table public.order_status_history (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  from_status public.order_status,
  to_status public.order_status not null,
  changed_by uuid references public.profiles(id),
  created_at timestamptz not null default now()
);

create table public.inventory_movements (
  id uuid primary key default gen_random_uuid(),
  product_id uuid not null references public.products(id),
  movement_type public.inventory_movement_type not null,
  quantity_delta numeric(12,3) not null,
  unit_cost numeric(12,2),
  order_id uuid references public.orders(id),
  note text,
  created_by uuid references public.profiles(id),
  created_at timestamptz not null default now()
);

create table public.stock_reservations (
  id uuid primary key default gen_random_uuid(),
  product_id uuid not null references public.products(id),
  order_id uuid not null references public.orders(id) on delete cascade,
  quantity numeric(12,3) not null check (quantity > 0),
  expires_at timestamptz not null,
  released_at timestamptz,
  consumed_at timestamptz,
  created_at timestamptz not null default now()
);

create index products_category_idx on public.products(category_id, active, sort_order);
create index orders_created_idx on public.orders(created_at desc);
create index orders_status_idx on public.orders(status, created_at desc);
create index inventory_product_idx on public.inventory_movements(product_id, created_at desc);
create index reservations_active_idx on public.stock_reservations(product_id, expires_at) where released_at is null and consumed_at is null;

create or replace function public.available_stock(p_product_id uuid)
returns numeric language sql stable as $$
  select greatest(
    coalesce(p.stock_quantity,0) -
    coalesce((select sum(r.quantity) from public.stock_reservations r
      where r.product_id=p.id and r.released_at is null and r.consumed_at is null and r.expires_at > now()),0),
    0)
  from public.products p where p.id=p_product_id;
$$;

alter table public.profiles enable row level security;
alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.customers enable row level security;
alter table public.customer_addresses enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.order_status_history enable row level security;
alter table public.inventory_movements enable row level security;
alter table public.stock_reservations enable row level security;

create policy "public read active categories" on public.categories for select using (active = true);
create policy "public read active products" on public.products for select using (active = true);

create or replace function public.is_staff()
returns boolean language sql stable security definer set search_path=public as $$
  select exists(select 1 from public.profiles p where p.id=auth.uid() and p.active and p.role in ('OWNER','ADMIN','STAFF'));
$$;

create policy "staff categories all" on public.categories for all to authenticated using (public.is_staff()) with check (public.is_staff());
create policy "staff products all" on public.products for all to authenticated using (public.is_staff()) with check (public.is_staff());
create policy "staff customers all" on public.customers for all to authenticated using (public.is_staff()) with check (public.is_staff());
create policy "staff addresses all" on public.customer_addresses for all to authenticated using (public.is_staff()) with check (public.is_staff());
create policy "staff orders all" on public.orders for all to authenticated using (public.is_staff()) with check (public.is_staff());
create policy "staff order items all" on public.order_items for all to authenticated using (public.is_staff()) with check (public.is_staff());
create policy "staff order history all" on public.order_status_history for all to authenticated using (public.is_staff()) with check (public.is_staff());
create policy "staff inventory all" on public.inventory_movements for all to authenticated using (public.is_staff()) with check (public.is_staff());
create policy "staff reservations all" on public.stock_reservations for all to authenticated using (public.is_staff()) with check (public.is_staff());
