-- Georgian and Armenian product names for every active product (was: Russian names shown in KA/HY).
-- Brands stay in Latin; Cyrillic brands are written in Latin for KA/HY (Uglevka, Tsarskaya, Ot Martina, Chistye Rosy).
update public.products p
   set name_i18n = jsonb_build_object('ru', p.name, 'ka', v.ka, 'hy', v.hy), updated_at = now()
  from (values
  ('DAV-CHEESE-MIX-450','შებოლილი ყველის ასორტი ~450 გ','Ապխտած պանրի տեսականի ~450 գ'),
  ('DAV-FISH-GEN-375','გენერალი ~375 გ','Գեներալ ~375 գ'),
  ('DAV-FISH-GEN-525','გენერალი ~525 გ','Գեներալ ~525 գ'),
  ('DAV-FISH-SHAM-001','შამაიკა','Շամայկա'),
  ('DAV-FISH-SIG-001','სიგი გამხმარი','Սիգ չորացրած'),
  ('DAV-FISH-STR-030','სტავრიდა გამხმარი 30 გ','Ստավրիդա չորացրած 30 գ'),
  ('DAV-FISH-STR-500','სტავრიდა ~500 გ','Ստավրիդա ~500 գ'),
  ('DAV-FISH-TUNA-030','თინუსი გამხმარი 30 გ','Թունա չորացրած 30 գ'),
  ('KRI-CHEESE-STICK-100','შებოლილი ყველი ჩხირები 100 გ','Ապխտած պանիր ձողիկներ 100 գ'),
  ('KRI-COG-ARA-003-050','ARARAT 3 წლიანი 0,5 ლ','ARARAT 3 տարեկան 0,5 լ'),
  ('KRI-COG-ARA-005-050','ARARAT 5 წლიანი 0,5 ლ','ARARAT 5 տարեկան 0,5 լ'),
  ('KRI-COG-ARA-AKH-050','ARARAT ახთამარი 10 წლიანი 0,5 ლ','ARARAT Ախթամար 10 տարեկան 0,5 լ'),
  ('KRI-ENERGY-BUM-FIRE-033','BUM Fire 0,33 ლ','BUM Fire 0,33 լ'),
  ('KRI-ENERGY-BURN-025','Burn 0,25 ლ','Burn 0,25 լ'),
  ('KRI-ENERGY-REDBULL-025','Red Bull 0,25 ლ','Red Bull 0,25 լ'),
  ('KRI-JUICE-CAPPY-ASST','Cappy — ასორტიმენტი','Cappy — տեսականի'),
  ('KRI-LIQ-JAG-050','Jägermeister 0,5 ლ','Jägermeister 0,5 լ'),
  ('KRI-MEAT-GYUMRI-600','ATENK ძეხვი „გიუმრი“ 600 გ','ATENK երշիկ «Գյումրի» 600 գ'),
  ('KRI-MEAT-JERKY-CHK-030','Jerky ქათმის 30 გ','Jerky հավի 30 գ'),
  ('KRI-MEAT-JERKY-MIX-060','Jerky მიქსი 60 გ','Jerky միքս 60 գ'),
  ('KRI-MEAT-JERKY-PORK-030','Jerky ღორის 30 გ','Jerky խոզի 30 գ'),
  ('KRI-MEAT-SUD-190','სუჯუკი 190 გ','Սուջուխ 190 գ'),
  ('KRI-MEAT-SUD-230','სუჯუკი აღმოსავლური 230 გ','Սուջուխ արևելյան 230 գ'),
  ('KRI-SNACK-MARTIN-080','Ot Martina მზესუმზირა 80 გ','Ot Martina արևածաղկի սերմ 80 գ'),
  ('KRI-SNACK-MARTIN-150','Ot Martina მზესუმზირა მარილიანი 150 გ','Ot Martina արևածաղկի սերմ աղած 150 գ'),
  ('KRI-SNACK-MARTIN-250','Ot Martina მზესუმზირა მარილიანი 250 გ','Ot Martina արևածաղկի սերմ աղած 250 գ'),
  ('KRI-SNACK-MARTIN-SMALL','Ot Martina მზესუმზირა','Ot Martina արևածաղկի սերմ'),
  ('KRI-SOFT-ARARAT-075','Ararat 0,75 ლ','Ararat 0,75 լ'),
  ('KRI-SOFT-ARARAT-COMP-100','Ararat კომპოტი ასორტი 1 ლ','Ararat կոմպոտ տեսականի 1 լ'),
  ('KRI-SOFT-ARARAT-PREM-097','Ararat Premium 0,97 ლ','Ararat Premium 0,97 լ'),
  ('KRI-SOFT-BOOM-100','BOOM ლიმონათი ასორტი 1 ლ','BOOM լիմոնադ տեսականի 1 լ'),
  ('KRI-SOFT-COLA-050','Coca-Cola 0,5 ლ','Coca-Cola 0,5 լ'),
  ('KRI-SOFT-FANTA-050','Fanta 0,5 ლ','Fanta 0,5 լ'),
  ('KRI-SOFT-LAIMON-050','Laimon Fresh 0,5 ლ','Laimon Fresh 0,5 լ'),
  ('KRI-SOFT-MIRINDA-050','Mirinda 0,5 ლ','Mirinda 0,5 լ'),
  ('KRI-SOFT-MIRINDA-OR-050','Mirinda Orange 0,5 ლ','Mirinda Orange 0,5 լ'),
  ('KRI-SOFT-MOONWALKER-024','Moon Walker ყავა ასორტი 0,24 ლ','Moon Walker սուրճ տեսականի 0,24 լ'),
  ('KRI-SOFT-PEPSI-050','Pepsi 0,5 ლ','Pepsi 0,5 լ'),
  ('KRI-SOFT-SNO-050','Sno წყალი 0,5 ლ','Sno ջուր 0,5 լ'),
  ('KRI-SOFT-SNO-100','Sno წყალი 1 ლ','Sno ջուր 1 լ'),
  ('KRI-SOFT-SPRITE-050','Sprite 0,5 ლ','Sprite 0,5 լ'),
  ('KRI-VER-MAR-BIA-050','Martini Bianco 0,5 ლ','Martini Bianco 0,5 լ'),
  ('KRI-VOD-ABS-050','Absolut 0,5 ლ','Absolut 0,5 լ'),
  ('KRI-VOD-CHIST-ROSY-050','Chistye Rosy 0,5 ლ','Chistye Rosy 0,5 լ'),
  ('KRI-VOD-FOR-MOON-050','FORTUNA PREMIUM 0,5 ლ','FORTUNA PREMIUM 0,5 լ'),
  ('KRI-VOD-FOR-PREM-050','FORTUNA GOLD 0,5 ლ','FORTUNA GOLD 0,5 լ'),
  ('KRI-VOD-TCH-050','Tchaikovsky 0,5 ლ','Tchaikovsky 0,5 լ'),
  ('KRI-VOD-TSAR-GOLD-050','Tsarskaya Gold 0,5 ლ','Tsarskaya Gold 0,5 լ'),
  ('KRI-VOD-TSAR-ORIG-050','Tsarskaya Original 0,5 ლ','Tsarskaya Original 0,5 լ'),
  ('KRI-VOD-UGL-050','Uglevka 0,5 ლ','Uglevka 0,5 լ'),
  ('KRI-VOD-UGL-070','Uglevka 0,7 ლ','Uglevka 0,7 լ'),
  ('KRI-WATER-LIKANI-060','Likani მინერალური წყალი 0,6 ლ','Likani հանքային ջուր 0,6 լ'),
  ('KRI-WATER-LIKANI-100','Likani მინერალური წყალი 1 ლ','Likani հանքային ջուր 1 լ'),
  ('KRI-WATER-NABEGLAVI-050','Nabeglavi 0,5 ლ','Nabeglavi 0,5 լ'),
  ('KRI-WATER-NABEGLAVI-100','Nabeglavi 1 ლ','Nabeglavi 1 լ'),
  ('KRI-WHI-JD-050','Jack Daniel''s Old No. 7 0,5 ლ','Jack Daniel''s Old No. 7 0,5 լ'),
  ('KRI-WINE-KC-WHITE-075','Kisi თეთრი ღვინო 0,75 ლ','Kisi սպիտակ գինի 0,75 լ'),
  ('KRI-WINE-MUKUZANI-075','მუკუზანი წითელი 0,75 ლ','Մուկուզանի կարմիր 0,75 լ'),
  ('KRI-WINE-SAPERAVI-075','საფერავი წითელი 0,75 ლ','Սափերավի կարմիր 0,75 լ'),
  ('KRI-WINE-SAPERAVI-ROSE-075','საფერავი როზე 0,75 ლ','Սափերավի ռոզե 0,75 լ'),
  ('KRI-WINE-SM-RK-075','SM რქაწითელი 0,75 ლ','SM Ռքածիթելի 0,75 լ'),
  ('KRI-WINE-SM-SAP-075','SM Saperavi 0,75 ლ','SM Saperavi 0,75 լ')
  ) v(sku, ka, hy)
 where p.sku = v.sku;
-- Beers are brand names: same in every language.
update public.products set name_i18n = jsonb_build_object('ru', name, 'ka', name, 'hy', name), updated_at = now()
 where sku in ('DAV-BEER-002','DAV-BEER-003','DAV-BEER-004','DAV-BEER-005');
